### ISSUE TITLE
General considerations

### ISSUE THREAD

**Issue by ThomazPom** [ThomazPom/Moz-Ext-UltimaDark#18]
Hey @EstherMoellman 

Did you know you can test the very edge version of UtlimaDark at any time? _`(as long i saved/shared the edits on github lol)`_

Download or pull the project in a folder, then visit `about:debugging#/runtime/this-firefox` with Firefox.

You will be able to load UltimaDark as a temporary addon by selecting the project location

**Comment by ThomazPom** [comment]
Last version of UltimaDark `(1.1.5)` is online, it solves a LOT of color issues, like parial darkening and is very interesting to see how it goes.
This version is not meant to full test (with ram and stuff) as you previously done becase it was not oriented on broken text/page/ram/contrast

However, i d'like you to take a look :)
Thank you

**Comment by EstherMoellman** [comment]
Hi there @ThomazPom ! Comment allez-vous? J'espère que tu vas très bien!

> Did you know you can test the very edge version of UtlimaDark at any time? _`(as long i saved/shared the edits on github lol)`_

Yeap! I know, but thank you anyway for your explanation.
I never downloaded your last version at GitHub, just because I preferred to test only those official versions with your approval.
Also, I really do intensive tests in each new version, and IMO is not worth testing unofficial versions from GitHub, because you're always going to see too much repetitive reports.
Not to mention that you may use GitHub for your partial progress, or little progress or even experimental progress, something private or intimate for you, and perhaps you don't want to test every GitHub' version of UltimaDark.

In the other hand, I have no problems in testing any UltimaDark version you want.
In principle, I'm going to test every new UD' version from FF' AMO.
But if you want/need, just send me a message, and I'll be glad to test any UD' version from any repo.

Passe un bon week-end! : ) 

PS: I'll test the new 1.1.5, and I'll report you the results.

**Comment by EstherMoellman** [comment]
@ThomazPom , complementing my previous message, I did my tests on V1.1.5 and here is my report:

1) Aesthetic results are... B-E-A-U-T-I-F-U-L!
But please remember, my focus is browser performance, so don't trust my aesthetic taste (I don't really have aesthetic taste for darkening add-ons). I always will prefer to loose in the aesthetic side, in order to gain in the browser performance side. And also I don't care too much about contrast details and stuff like that. If most of the pages are darkening, and if the browser performance is fine... then for me this will be enough.
But comparing with other darkening add-ons, I think that UltimaDark has wonderful and beautiful aesthetics results.
Also some contrasts improved a lot in V.1.1.5.

2) Darkening is working fine for most of the pages.
I found few pages with issues, and already reported them in old and new opened issues here in your GitHub.
It's worth mentioning that in my tests I don't chose webpages because are popular or because I use them. I test webpages randomly, in order to try to find useful issues for improving UltimaDark. Therefore, the "high priority" of this issues is not related to the webpages, but to the issues inside them, issues that may drive you to create fixes for other webpages.
Also it's worth mentioning that it'll be impossible to solve 100% of the webpage issues. I just report issues to you in case you can improve UltimaDark. But if you can't fix everything, **no problem!**, it's totally understandable. Also remember that sometimes when you fix something for one page, at the same time you broke something to another page. So the idea is not to fix everything, but to try to find a good balance for most of the pages.

3) Webpage loading speed still is great in V1.1.5, IMO is the better loading speed among other darkening add-ons.
RAM/CPU: No big changes in V1.1.5, in average (±)2MB... similar to Dark Reader add-on. Testing all pages in one tab, makes RAM = (±) 1.5MB. I think that in the future a (±)1MB will be great and enough.

**Comment by EstherMoellman** [comment]
@ThomazPom , if you already read my comments, please close this issue in order to keep your GitHub clean and organized. Thanks! : )

**Comment by ThomazPom** [comment]
I consider this issue as the thread where we can discuss of general things and decide what to do
Should i close it ?

**Comment by EstherMoellman** [comment]
I prefer to have "open issues" only when something is under work or developing or pending etc.
In the case of discussions about general things etc, personally I think is more healthy to have different opened/closed issues, because in the future if you need, it will be easier to identify different discussions. If all our discussions are going to be in one giant long issue, in the future it may be complicated to find stuff.
In brief, I prefer to close this issue, and let's open new issues for new discussions/general things.
But mon ami, your house, your rules : ) ... keep open or closed whatever makes you comfortable. You always have the last word!
