### ISSUE TITLE
Question about "i.reddit.com" whitelisted (Priority Level: Low)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#22]
I use "https://i.reddit.com/" all the time. But I have my own CSS reddit' customized dark theme (which also blocks some reddit' garbage). So I tried to whitelist "https://i.reddit.com/" at UltimaDark.

When I select precision of 3 letters, it appears:
*://i.reddit.com/*
*://*.i.reddit.com/*
*://www.redditstatic.com/*
*://*.www.redditstatic.com/*

If I don't include "redditstatic" then UltimaDark doesn't whitelist "i.reddit.com".
The problem is that whitelisting "redditstatic" also whitelists "old.reddit.com"... and I don't want "old.reddit.com" whitelisted.

So, my question is: Am I doing something wrong?
Or is this a UltimaDark' whitelist bug?

Thks! : )

**Comment by ThomazPom** [comment]
i.reddit fetchs its styles from redditstatic.com.
This is why if you don't exclude redditstatic, the redditstatics styles gets edited and the website ends dark
This is so far the normal behaviour.

**This can cause problem if you wand to use i.reddit.com in white and www.reddit.com in black as they both use redditstatic.**

To fix : 
I could detect  when a  blacklisted website(i.redit there) loads a style on another domain (like redditstatic.com) and ignore it
The blacklist would be shorter, because you wolud not have to deal with Content Delivery Networks domains as redstatic.

**Comment by ThomazPom** [comment]
This is fixed in the next version of ultimadark

**Comment by ThomazPom** [comment]
It makes a shorter blacklist to check, better performance

**Comment by ThomazPom** [comment]
And it makes more sense for user

**Comment by ThomazPom** [comment]
1.1.6 is availble and includes this edit
