### ISSUE TITLE
Exclusions don't seem to work very well when on a port

### ISSUE THREAD

**Issue by TheTechRobo** [ThomazPom/Moz-Ext-UltimaDark#31]
For example `localhost:8000` doesn't get excluded even though I ask it to.

**Comment by ThomazPom** [comment]
I checked with 
*://localhost:3443/*

Works as intended

**Comment by gaardhus** [comment]
For me I had to exclude both the base localhost and the specific port

ie

```
*://localhost/*
*://*.localhost/*
*://localhost:8666/*
*://*.localhost:8666/*
```

**Comment by gabeclarke** [comment]
Sorry if its more appropriate to open a new issue, but I'm also struggling to exclude ports. 

I host servers outside of localhost but still internal to my network, I did not see any way to handle this case in the mozilla page on this topic. How would you exclude for example 192.168.1.10:3333, if 192.168.1.10 is not localhost? I need this use case because some of my apps can and do want to leverage Ultima, some are incompatible.
