### ISSUE TITLE
Disable / block clearing of browser history

### ISSUE THREAD

**Issue by arb-c** [ThomazPom/Moz-Ext-UltimaDark#32]
(Paris, France)

My browser history is my 'work notebook' (I have the _No History_ add-on which allows me to store in the browser history only what I want, and I curate it religiously). Is there a way to disable / block UltimaDark from touching the history? (I understand this might degrade its power on certain websites.)

**Comment by ThomazPom** [comment]
As far a i know, ultimadark does not interact with history of the browser. What makes you think ultimadark is touching you history ?

**Comment by arb-c** [comment]
(Paris, France)

> As far as i know, ultimadark does not interact with browser history . What makes you think ultimadark is touching yous history ?

The first item in the "Permissions" box ( https://addons.mozilla.org/en-US/firefox/addon/ultimadark/ )

![image](https://user-images.githubusercontent.com/19972033/157085547-5ad38659-e78c-49f7-8cb4-04ab7772b0d1.png)

**Comment by ThomazPom** [comment]
Oh.

This is due to the manifest https://github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/manifest.json
it declares using browsingData, for some technical reason, i'll verify later. (I think it is needed to edit on the fly responses)


I guarantee you UltimaDark does will never affect your browsing history

Please remember That UltimaDark is still higly experimental, and may affect a lot your internet experience.

About 1/ 15 website is still broken under ultimadark.

**Comment by ThomazPom** [comment]
I took a look, UltimaDark only needs browsingData API to clear browser  cache and this will not affect browser history
