### ISSUE TITLE
Significant performance regression in 1.5.29/ 1.5.31

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#61]
1.5.29 tested 5 times avg 73.5

![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/8f3a12ae-c35e-4419-9750-3d472fd3f6a5)

1.5.28 tested avg 80 

![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/acbc31bd-5313-483a-b7e0-157ed26490c8)

Site background is also being improperly recolored in 1.5.29 but I will open a separate issue for that.

**Comment by ThomazPom** [comment]
I've just released two versions of UltimaDark: 1.5.30 and 1.5.31.

Both address a portion of the performance drop, with 1.5.30 fully resolving the issue but presenting notable drawbacks.

In 1.5.30, I reinstated the UltimaDark "Direct window export system," despite reservations due to its highly aggressive nature (acknowledging that UltimaDark philosophy embraces aggressive techniques). However, this approach may encounter issues when websites use polyfills with the same name as a function employed by UltimaDark, potentially causing breaks until I explicitly forbid such polyfills. (I've identified one instance on commons.wikimedia.org, but there could be numerous possibilities.) The install time is 2.0566037735849 seconds (ranging from 1ms to 5ms). After identifying and forbidding a polyfill, it needs to be injected preemptively across all websites, proving useful very rarely.

In 1.5.31, I disabled the UltimaDark "Direct window export system," opting for the code to leverage the native Firefox export system, which is 60% slower in website post-load operations. The install time remains 2.0566037735849 seconds (with a range of 1ms to 6ms).

The Speedometer2.1 score from https://browserbench.org/Speedometer2.1/ aims to measure page load speed but also encompasses post-load operations. The use of the native Firefox export system results in a 60% slowdown in these operations, causing an 8% drop in the overall score.

It's crucial to note that these post-load operation delays, to the best of my knowledge, are imperceptible to UltimaDark users as they are non-blocking and have no impact on webpage loading.

## Visible demonstration
This slowdown becomes evident in a specialized test: https://jsben.ch/GP26t
#### 1.5.30 : 50% speed against common comparator
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/b3d5893c-fc75-4b2e-a92e-de85e08ebeed)


#### 1.5.31 20% speed against common comparator
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/92069583-0921-44fb-b4c7-c03792a35c02)

The question arises whether an 8% speed decrease, potentially imperceptible to users, justifies increased code complexity and some rare websites not being directly covered.

For now, I will maintain the native Firefox export system. If the consequences of this decision become too perceptible, I have made the transition back to the UltimaDark "Direct window export system" very straightforward

https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/53#issuecomment-1889303281

**Comment by Vintagemotors** [comment]
1.5.31 has the same performance regression as 1.5.29 avg 73
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/051618af-fa7a-45ae-b92c-7d37c9792ee7)

**Comment by Vintagemotors** [comment]
This is a run immediately after with 1.5.28 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/5f03ad13-4bd8-4ea5-83bb-21a7a9669999)

**Comment by ThomazPom** [comment]
1.5.30 was refused by Mozilla because i've published 1.5.31 while 1.5.30 was still under review.
I've published 1.5.32 and fixed the comment text

**Comment by Vintagemotors** [comment]
Performance regression largely reversed by 1.5.32 (1.5.30) I am seeing an average of 79 R/M which can be explained by background processes.

**Comment by ThomazPom** [comment]
Although the performance drop is quantifiable, ranging from 5% to 20% according to browserbench metrics, my understanding on page loading leads me to believe that this decline is non blocking for webpage , making it likely probably non perceptible to users.

Interestingly, I occasionally observe comparable scores between the two versions on browserbench, and I haven't identified a clear explanation for this.

**Comment by Vintagemotors** [comment]
Browserbench 2.0 and 2.1 differ in that 2.0 had a delay timer added in some cases which 2.1 removes and 2.1 uses newer versions of the frameworks used in the test which changed their performance characteristics. Generally speaking 2.1 should be slightly faster than 2.0 but I use 2.0 for testing because I have a larger sample size in it and the results are generally consistent between runs.

**Comment by Vintagemotors** [comment]
> Interestingly, I occasionally observe comparable scores between 1.5.31 & 1.5.32
I have not encountered this.

**Comment by Vintagemotors** [comment]
Within margin of error on 1.5.33
