### ISSUE TITLE
Detect dark theme

### ISSUE THREAD

**Issue by quivenda** [ThomazPom/Moz-Ext-UltimaDark#68]
Hi, thanks for the great extensions.

It is possible to detect dark theme without excluding websites?

Dark Reader has these functions, but it seems to be buggy because you need to disable and enable it to detect the dark theme. I hope that feature implemented on UltimaDark.

**Comment by Vintagemotors** [comment]
UltimaDark does not trust any website to completely implement a dark theme on its own which is why the thresholds are based on relative colors instead of having a global excluded site list baked in. No websites with native dark theme change the coloring of image backgrounds the way ImageEdition does which means UltimaDark should be allowed to run on 100% of websites once the ImageEdition rewrite is completed.
