### ISSUE TITLE
Suggested UX improvements for whitelist / included-only / exclude-by-default mode

### ISSUE THREAD

**Issue by yump** [ThomazPom/Moz-Ext-UltimaDark#83]
The extension can be switched to whitelist mode (where only sites matched by the "darken these" list are darkened), but it's currently kind of clunky.

1. Switching to whitelist mode requires removing `<all_urls>` and `*://*/*` from the whitelist, *but not* the example filter, because if the whitelist is blank it gets regenerated with the default content.  Also, as far as I can tell both of those filters appear to have the same effect (match everything), but the first looks like it might be a comment or something. I had to experiment a lot to determine that whitelist mode was possible, and even uninstalled the extension once in frustration.

    There should be a preference to explicitly toggle darken-by-default on or off, and the UI should clearly explain the precedence between the whitelist and blacklist.

2. There is a button to exclude the current site, but no button to *in*clude it. So the current whitelisting workflow is to click the exclude button, then cut-and-paste from the exclude list to the "darken these" list.

    There should be an include-current-site button.

3. You have to scroll the popup panel to access the whitelist, because the other content is excessively prominent and the order is jumbled.

    Suggested layout for the popup panel:

    ```
    "Ultima Dark <version>" <enable/disable toggle>
    <donate link>
    <exclude list>
    <darken list>
    <exclude> <darken> <refresh page>
    <precision setting> (with tooltip indicating what that means; currently seems to do nothing?)
    <darken by default toggle>
    <link to match patterns reference>
    ----
    <cache system toggle>
    <image edition toggle> (perhaps change name to "image adjustment" or "transform images")
    <advanced settings button>
    ----
    <sources & update>
    <rate & about>
    ```

    I also added in a refresh button, because it would allow quick including/excluding and testing with only the mouse.

(Multiple names for this used in title to aid searches.)

**Comment by ThomazPom** [comment]
Thank you for your detailed feedback. I find most of your points to be true, and I'll use this issue as one of my checklists during UI development.

As you discovered, since `<all_urls>` and `*://*/*` are broader than any other site-specific filters, they catch everything and override more narrow filters. These expressions are part of Mozilla MDN Match Patterns, as referenced [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) and in the examples [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#examples).

I'll work on refining the whitelist mode and UI improvements you suggested. Thanks again for your insights.

You can access this link at anytime from UltimaDark menu
![image](https://github.com/user-attachments/assets/d4b5e5f4-f1ea-4f9d-a77f-e563df327813)

**Comment by Vintagemotors** [comment]
Merged with feature requests - can be reopened when/if needed.

**Comment by ThomazPom** [comment]
Having it in the ctx menu is a nice idea
