### ISSUE TITLE
www.eurogamer.net not always dark

### ISSUE THREAD

**Issue by cnieuweboer** [ThomazPom/Moz-Ext-UltimaDark#91]
When www.eurogamer.net initially loads ultimadark applies properly. When clicking the horizon menu items at the top, and the eurogamer icon at the very top a few times, randomly the page loads without applying ultimadark. Ctrl+r fixes it every time.

**Comment by ThomazPom** [comment]
Hi
This issue is related to caching and i'ts a very interesing case. When you navigate through this website and some elements are not styled correctly, its because the browser managed somehow to cache content before ultimadark intervention and is then loading cached content without the ultimadark styles applied.

**Comment by nitschis** [comment]
Here is another one, it's only dark if you refresh the page: https://www.preisjaeger.at/

**Comment by chmichael** [comment]
@ThomazPom Yes caching showhow is confusing UltimaDark usually when you go back into your previous page. I have disabled smartcache and use 10GB disk cache on my nvme drive so Firefox uses the cache a lot.

**Comment by Vintagemotors** [comment]
www.eurogamer.net appears to be fixed by 1.5.56, as does https://www.preisjaeger.at/ - please confirm.

**Comment by cnieuweboer** [comment]
eurogamer still has the same issue for me. In particular the playstation category seems to trigger it.

**Comment by ThomazPom** [comment]
@chmichael I’ve identified and resolved the two underlying bugs.

**Comment by cnieuweboer** [comment]
Confirmed. Fixed for me now.
